services:
  - type: web
    name: id-shield
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: LOG_LEVEL
        value: INFO
